# Generated by Django 2.1.8 on 2019-11-19 04:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('addr', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系地址')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'xxxx',
                'verbose_name': 'xxxxxx',
                'db_table': 'shop_buyer',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=32, verbose_name='收货人姓名')),
                ('password', models.CharField(max_length=32, verbose_name='收货地址邮编')),
                ('phone', models.CharField(max_length=32, verbose_name='收货人电话')),
                ('addr', models.CharField(max_length=32, verbose_name='收货地址')),
                ('isdefault', models.BooleanField(default=True, verbose_name='是默认地址')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收货地址')),
            ],
            options={
                'verbose_name_plural': '收货地址',
                'verbose_name': '收货地址',
                'db_table': 'shop_address',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods', verbose_name='所属商品')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'verbose_name': '购物车',
                'db_table': 'eshop_cart',
            },
        ),
        migrations.CreateModel(
            name='GoodsRelave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('start_time', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单id')),
                ('paymethod', models.IntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝'), (4, '银联支付')], default=3, verbose_name='支付方式')),
                ('totalcount', models.IntegerField(default=0, verbose_name='商品数量')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('freight', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='订单运费')),
                ('status', models.IntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('paynumber', models.CharField(default='', max_length=128, verbose_name='支付编号')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Address', verbose_name='地址')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
                'db_table': 'eshop_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('image', models.ImageField(upload_to='img', verbose_name='图片')),
                ('unite', models.CharField(default='500g', max_length=20, verbose_name='单位')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods', verbose_name='所属商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name_plural': '订单详情',
                'verbose_name': '订单详情',
                'db_table': 'eshop_orderdetail',
            },
        ),
    ]
