# Generated by Django 2.1.8 on 2019-11-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': '买家', 'verbose_name_plural': '买家'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='shop_cart',
        ),
        migrations.AlterModelTable(
            name='order',
            table='shop_order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='shop_orderdetail',
        ),
    ]
