# Generated by Django 2.1.8 on 2019-11-20 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20191119_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
