# Generated by Django 2.1.8 on 2019-11-20 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='key',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=200, null=True, verbose_name='关键字'),
        ),
    ]
