# Generated by Django 2.1.8 on 2019-11-21 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20191120_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='buyer.Order'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='key',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
