# Generated by Django 2.1.8 on 2019-11-23 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('buyer', '0007_auto_20191122_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_discount', models.PositiveIntegerField(default=0, verbose_name='折扣')),
                ('goods_coupon', models.PositiveIntegerField(default=0, verbose_name='商品折扣')),
                ('store_coupon', models.PositiveIntegerField(default=0, verbose_name='店铺折扣')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Goods')),
            ],
        ),
    ]
