# Generated by Django 2.1.8 on 2019-11-19 04:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='价格')),
                ('image', models.ImageField(upload_to='img', verbose_name='图片')),
                ('number', models.IntegerField(verbose_name='库存')),
                ('description', models.TextField(verbose_name='描述')),
                ('productdate', models.DateField(verbose_name='生产日期')),
                ('shelflife', models.IntegerField(verbose_name='保质期')),
                ('up', models.IntegerField(default=0, verbose_name='商品上下架')),
                ('sales', models.IntegerField(null=True, verbose_name='销量')),
                ('unite', models.CharField(default='500g', max_length=20, verbose_name='单位')),
            ],
            options={
                'verbose_name_plural': '商品',
                'verbose_name': '商品',
                'db_table': 'shop_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img', verbose_name='图片地址')),
                ('description', models.TextField(max_length=32, verbose_name='图片描述')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods', verbose_name='所属商品')),
            ],
            options={
                'verbose_name_plural': '商品图片',
                'verbose_name': '商品图片',
                'db_table': 'shop_goodsimg',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='商品类型')),
                ('description', models.TextField(max_length=32, verbose_name='商品类型描述')),
                ('picture', models.ImageField(upload_to='buyer/images')),
            ],
            options={
                'verbose_name_plural': '商品类型',
                'verbose_name': '商品类型',
                'db_table': 'shop_goodstype',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=33, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='用户头像')),
                ('address', models.CharField(blank=True, max_length=44, null=True, verbose_name='地址')),
                ('cardid', models.CharField(max_length=18, verbose_name='身份证')),
            ],
            options={
                'verbose_name_plural': '卖家',
                'verbose_name': '卖家',
                'db_table': 'shop_seller',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='店铺名称')),
                ('address', models.CharField(max_length=30, verbose_name='发货地址')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='店铺描述')),
                ('image', models.ImageField(upload_to='img', verbose_name='LOGO')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('money', models.FloatField(verbose_name='注册资金')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Seller', verbose_name='所属卖家')),
            ],
            options={
                'verbose_name_plural': '店铺',
                'verbose_name': '店铺',
                'db_table': 'shop_store',
            },
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='店铺类型')),
                ('description', models.TextField(verbose_name='店铺类型描述')),
            ],
            options={
                'verbose_name_plural': '店铺类型',
                'verbose_name': '店铺类型',
                'db_table': 'shop_storetype',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='storetype',
            field=models.ManyToManyField(to='store.StoreType', verbose_name='店铺类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.GoodsType', verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='所属店铺'),
        ),
    ]
